services:

  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: php_app
    volumes:
      - ./:/var/www
    ports:
      - "8000:8000"
      - "5173:5173"
    depends_on:
      - mysql
      - rabbitmq
    tty: true

  mysql:
    image: mysql:8
    container_name: mysql_db
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: app
      MYSQL_USER: app
      MYSQL_PASSWORD: app
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql

  rabbitmq:
    image: rabbitmq:3-management
    container_name: rabbitmq
    ports:
      - "5672:5672"
      - "15672:15672"

  mailhog:
    image: mailhog/mailhog
    container_name: mailhog
    ports:
      - "1025:1025"
      - "8025:8025"

volumes:
  mysql_data: